name: ci

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Maven Install
        run: mvn install -B -V -DskipTests -Dair.check.skip-all
      - name: Maven Tests
        run: mvn install -B -P ci
